# Generated by Django 5.2.5 on 2025-08-29 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent',
            new_name='stripe_checkout_session_id',
        ),
    ]
